import { RestaurantData, MenuItem, Category } from './types';

const skylineCategories: Category[] = [
  { id: 'cat-101', restaurant_id: 'rest-001', name: 'Starters & Tandoor', description: 'Sizzling tandoori kebabs and crispy appetizers', sort_order: 1, active: true },
  { id: 'cat-102', restaurant_id: 'rest-001', name: 'Dum Biryani & Rice', description: 'Aromatic basmati rice cooked with royal spices', sort_order: 2, active: true },
  { id: 'cat-103', restaurant_id: 'rest-001', name: 'Main Course - Gravies', description: 'Rich North Indian curries cooked in house gravy', sort_order: 3, active: true },
  { id: 'cat-104', restaurant_id: 'rest-001', name: 'Indo-Chinese Delights', description: 'Popular oriental starters and wok-tossed noodles', sort_order: 4, active: true },
  { id: 'cat-105', restaurant_id: 'rest-001', name: 'Rotis & Indian Breads', description: 'Freshly baked tandoori breads, naans, and parathas', sort_order: 5, active: true },
  { id: 'cat-106', restaurant_id: 'rest-001', name: 'South Indian & Snacks', description: 'Crispy dosas, vada, samosas, and street snacks', sort_order: 6, active: true },
  { id: 'cat-107', restaurant_id: 'rest-001', name: 'Desserts & Sweets', description: 'Traditional Indian sweets and ice cream sundaes', sort_order: 7, active: true },
  { id: 'cat-108', restaurant_id: 'rest-001', name: 'Beverages & Mocktails', description: 'Refreshing lassis, fresh juices, and signature coolers', sort_order: 8, active: true },
];

const skylineMenuItems: MenuItem[] = [
  // --- STARTERS & TANDOOR (12 ITEMS) ---
  {
    id: 'item-101',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Paneer Tikka Angara',
    description: 'Fresh cottage cheese marinated in spicy yoghurt, degi mirch, and cooked over charcoal coals.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    price: 340,
    discount_price: 299,
    food_type: 'veg',
    spice_level: 2,
    ingredients: ['Paneer', 'Yoghurt', 'Kashmiri Chili', 'Garam Masala', 'Bell Peppers'],
    allergens: ['Dairy'],
    tags: ['Chef Special', 'Grill'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-102',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Tandoori Chicken (Half)',
    description: 'Juicy bone-in chicken marinated overnight in tandoori spices and roasted to perfection in clay oven.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    price: 420,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Chicken', 'Yoghurt', 'Mustard Oil', 'Tandoori Spices', 'Lemon'],
    allergens: ['Dairy'],
    tags: ['Classic', 'Clay Oven'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-103',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Chicken Malai Tikka',
    description: 'Boneless chicken cubes marinated in cashew paste, fresh cream, cheese, and cardamom.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
    price: 380,
    discount_price: 350,
    food_type: 'non-veg',
    spice_level: 0,
    ingredients: ['Chicken', 'Cashew Paste', 'Cream', 'Cheese', 'Cardamom'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Mild', 'Creamy'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 3,
  },
  {
    id: 'item-104',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Hara Bhara Kebab',
    description: 'Pan-fried patties made with spinach, green peas, mashed potatoes, and roasted gram flour.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    price: 280,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Spinach', 'Green Peas', 'Potato', 'Cashews', 'Gram Flour'],
    allergens: ['Nuts'],
    tags: ['Healthy', 'Veg Starter'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-105',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Mutton Seekh Kebab',
    description: 'Minced mutton blended with aromatic spices, skewers charcoal grilled to juicy perfection.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    price: 490,
    discount_price: 450,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Minced Mutton', 'Onion', 'Ginger', 'Royal Spices', 'Mint'],
    allergens: [],
    tags: ['Royal Taste', 'Grill'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 5,
  },
  {
    id: 'item-106',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Amritsari Fish Fry',
    description: 'Crispy carom seed (ajwain) seasoned fish fillets fried in spiced gram flour batter.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
    price: 440,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Basa Fish', 'Ajwain', 'Besan', 'Lemon', 'Chaat Masala'],
    allergens: ['Fish'],
    tags: ['Crispy', 'Seafood'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 6,
  },
  {
    id: 'item-107',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Tandoori Mushroom Tikka',
    description: 'Button mushrooms stuffed with spiced cheese and charbroiled in tandoori marinade.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    price: 310,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Mushrooms', 'Processed Cheese', 'Yoghurt', 'Garam Masala'],
    allergens: ['Dairy'],
    tags: ['Vegetarian'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 7,
  },
  {
    id: 'item-108',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Dahi Ke Kebab',
    description: 'Crispy fried patties stuffed with hung curd, paneer, coriander, and subtle green spices.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    price: 295,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Hung Yoghurt', 'Paneer', 'Green Chili', 'Bell Pepper'],
    allergens: ['Dairy', 'Gluten'],
    tags: ['Melt-in-mouth'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 8,
  },
  {
    id: 'item-109',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Chicken Tangdi Kebab (3 pcs)',
    description: 'Marinated chicken drumsticks roasted with black pepper and royal tandoori spices.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    price: 410,
    discount_price: 380,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Chicken Drumsticks', 'Black Pepper', 'Yoghurt', 'Butter'],
    allergens: ['Dairy'],
    tags: ['Popular'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 9,
  },
  {
    id: 'item-110',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Tandoori Soya Chaap',
    description: 'Protein-rich soya chaap marinated in spicy tandoori masala and grilled over coals.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    price: 320,
    discount_price: null,
    food_type: 'veg',
    spice_level: 2,
    ingredients: ['Soya Chaap', 'Yoghurt', 'Mustard Oil', 'Kasuri Methi'],
    allergens: ['Soy', 'Dairy'],
    tags: ['High Protein', 'Veg'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 10,
  },
  {
    id: 'item-111',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Prawns Koliwada',
    description: 'Crispy deep-fried prawns tossed in spicy Mumbai coastal chili garlic batter.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
    price: 520,
    discount_price: 480,
    food_type: 'non-veg',
    spice_level: 3,
    ingredients: ['Tiger Prawns', 'Red Chili', 'Garlic', 'Gram Flour'],
    allergens: ['Shellfish'],
    tags: ['Spicy', 'Seafood'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 11,
  },
  {
    id: 'item-112',
    restaurant_id: 'rest-001',
    category_id: 'cat-101',
    name: 'Egg Tikka Roast',
    description: 'Boiled eggs coated with spicy onion-tomato masala and seared on a hot tawa.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    price: 240,
    discount_price: null,
    food_type: 'egg',
    spice_level: 2,
    ingredients: ['Hard Boiled Eggs', 'Onion', 'Tomato', 'Curry Leaves'],
    allergens: ['Egg'],
    tags: ['Egg Special'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 12,
  },

  // --- DUM BIRYANI & RICE (8 ITEMS) ---
  {
    id: 'item-201',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Kolkata Special Mutton Biryani',
    description: 'Fragrant long-grain basmati rice layered with tender mutton, boiled egg, and golden spiced potato.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    price: 495,
    discount_price: 450,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Basmati Rice', 'Mutton', 'Potato', 'Egg', 'Ghee', 'Saffron', 'Meetha Attar'],
    allergens: ['Dairy', 'Egg'],
    tags: ['Signature', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-202',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Hyderabadi Chicken Dum Biryani',
    description: 'Traditional slow-cooked dum biryani packed with spicy marinated chicken and caramelized onions.',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    price: 390,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 3,
    ingredients: ['Basmati Rice', 'Chicken', 'Fried Onions', 'Mint', 'Coriander', 'Ghee'],
    allergens: ['Dairy'],
    tags: ['Spicy', 'Popular'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-203',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Special Paneer Dum Biryani',
    description: 'Long grain basmati rice cooked with marinated paneer cubes, saffron milk, and fried cashews.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    price: 340,
    discount_price: 310,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Basmati Rice', 'Paneer', 'Saffron', 'Cashews', 'Biryani Spices'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Veg Biryani'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 3,
  },
  {
    id: 'item-204',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Royal Vegetable Dum Biryani',
    description: 'Seasonal garden vegetables dum-cooked with basmati rice, Kewra water, and aromatic herbs.',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    price: 290,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Basmati Rice', 'Carrots', 'French Beans', 'Cauliflower', 'Ghee'],
    allergens: ['Dairy'],
    tags: ['Vegetarian'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-205',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Egg Dum Biryani',
    description: 'Basmati rice layered with boiled eggs roasted in rich caramelized onion and garlic masala.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    price: 310,
    discount_price: null,
    food_type: 'egg',
    spice_level: 2,
    ingredients: ['Basmati Rice', 'Eggs', 'Fried Onions', 'Ghee', 'Biryani Masala'],
    allergens: ['Egg', 'Dairy'],
    tags: ['Egg Delight'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 5,
  },
  {
    id: 'item-206',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Jeera Rice (Ghee Tossed)',
    description: 'Aromatic basmati rice tempered with cumin seeds and pure desi ghee.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    price: 180,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Basmati Rice', 'Cumin Seeds', 'Desi Ghee', 'Coriander'],
    allergens: ['Dairy'],
    tags: ['Staple'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 6,
  },
  {
    id: 'item-207',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Kashmiri Pulao',
    description: 'Sweet and fragrant basmati rice tossed with fresh fruits, dry fruits, saffron, and paneer.',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    price: 280,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Basmati Rice', 'Apples', 'Raisins', 'Cashews', 'Saffron', 'Paneer'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Mild & Sweet'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 7,
  },
  {
    id: 'item-208',
    restaurant_id: 'rest-001',
    category_id: 'cat-102',
    name: 'Steamed Basmati Rice',
    description: 'Fluffy long-grain steamed premium basmati rice.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    price: 140,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Basmati Rice', 'Water'],
    allergens: [],
    tags: ['Simple'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 8,
  },

  // --- MAIN COURSE - GRAVIES (12 ITEMS) ---
  {
    id: 'item-301',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Butter Chicken Masala',
    description: 'Smokey tandoori chicken cooked in a velvety tomato, cashew nut, and butter gravy with kasuri methi.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    price: 440,
    discount_price: 399,
    food_type: 'non-veg',
    spice_level: 1,
    ingredients: ['Chicken', 'Tomatoes', 'Fresh Cream', 'Butter', 'Cashew Paste', 'Kasuri Methi'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Crowd Favorite', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-302',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Dal Makhani Special',
    description: 'Black lentils slow cooked overnight on charcoal, finished with fresh churned butter and cream.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    price: 310,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Urad Dal', 'Rajma', 'Butter', 'Cream', 'Ginger Garlic Paste'],
    allergens: ['Dairy'],
    tags: ['Comfort Food', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-303',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Paneer Butter Masala',
    description: 'Soft cottage cheese cubes cooked in rich creamy onion tomato gravy seasoned with royal spices.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    price: 360,
    discount_price: 329,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Paneer', 'Butter', 'Cream', 'Cashew Paste', 'Tomatoes'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Veg Favorite'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 3,
  },
  {
    id: 'item-304',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Kadai Chicken',
    description: 'Juicy chicken pieces tossed with thick chopped onion, bell peppers, and coarse hand-ground kadai masala.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    price: 420,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Chicken', 'Capsicum', 'Onion', 'Coriander Seeds', 'Whole Red Chili'],
    allergens: [],
    tags: ['Spicy Curry'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-305',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Mutton Rogan Josh',
    description: 'Traditional Kashmiri style tender mutton curry cooked with ratanjot and fennel spices.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    price: 540,
    discount_price: 499,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Mutton', 'Kashmiri Chili', 'Fennel Powder', 'Mustard Oil', 'Ghee'],
    allergens: ['Dairy'],
    tags: ['Kashmiri Special'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 5,
  },
  {
    id: 'item-306',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Palak Paneer',
    description: 'Fresh spinach puree simmered with cottage cheese cubes, garlic, and tempered with cumin ghee.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    price: 330,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Spinach', 'Paneer', 'Garlic', 'Ghee', 'Cream'],
    allergens: ['Dairy'],
    tags: ['Healthy Veg'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 6,
  },
  {
    id: 'item-307',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Chicken Korma Awadhi',
    description: 'Rich royal chicken curry cooked in almond, cashew nut, and saffron infused golden gravy.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    price: 460,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 1,
    ingredients: ['Chicken', 'Almonds', 'Cashews', 'Saffron', 'Kewra Water'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Royal Cuisine'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 7,
  },
  {
    id: 'item-308',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Malai Kofta',
    description: 'Soft potato paneer balls stuffed with dry fruits, served in creamy golden cashew gravy.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=600&q=80',
    price: 370,
    discount_price: 340,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Paneer', 'Potato', 'Cashews', 'Raisins', 'Cream'],
    allergens: ['Dairy', 'Nuts', 'Gluten'],
    tags: ['Rich Veg'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 8,
  },
  {
    id: 'item-309',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Fish Curry Bengal Style',
    description: 'Fresh katla/rohu fish cooked in mustard oil, panch phoron spices, and green chilis.',
    image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80',
    price: 410,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Fresh Fish', 'Mustard Paste', 'Mustard Oil', 'Turmeric', 'Green Chili'],
    allergens: ['Fish', 'Mustard'],
    tags: ['Bengali Classic'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 9,
  },
  {
    id: 'item-310',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Chana Masala Amritsari',
    description: 'Chickpeas cooked in dark roasted tea leaf infused onion gravy with pomegranate powder.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80',
    price: 270,
    discount_price: null,
    food_type: 'veg',
    spice_level: 2,
    ingredients: ['Chickpeas', 'Anardana', 'Amchur', 'Ginger', 'Green Chili'],
    allergens: [],
    tags: ['North Indian'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 10,
  },
  {
    id: 'item-311',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Egg Curry Masala (2 Eggs)',
    description: 'Fried boiled eggs simmered in rich spicy tomato onion gravy with fresh coriander.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80',
    price: 260,
    discount_price: null,
    food_type: 'egg',
    spice_level: 2,
    ingredients: ['Boiled Eggs', 'Onion', 'Tomato', 'Garam Masala'],
    allergens: ['Egg'],
    tags: ['Egg Curry'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 11,
  },
  {
    id: 'item-312',
    restaurant_id: 'rest-001',
    category_id: 'cat-103',
    name: 'Yellow Dal Tadka',
    description: 'Yellow arhar dal tempered with cumin, garlic, dry red chili, and desi ghee.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    price: 240,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Toor Dal', 'Desi Ghee', 'Garlic', 'Cumin', 'Asafoetida'],
    allergens: ['Dairy'],
    tags: ['Home Style'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 12,
  },

  // --- INDO-CHINESE DELIGHTS (8 ITEMS) ---
  {
    id: 'item-401',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Chili Chicken Dry',
    description: 'Crispy fried chicken chunks tossed with capsicum, onions, dark soy sauce, and green chilis.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    price: 360,
    discount_price: 320,
    food_type: 'non-veg',
    spice_level: 3,
    ingredients: ['Chicken', 'Capsicum', 'Dark Soy Sauce', 'Chili Sauce', 'Spring Onion'],
    allergens: ['Soy', 'Gluten'],
    tags: ['Indo-Chinese', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-402',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Veg Hakka Noodles',
    description: 'Wok-tossed noodles with crunchy shredded vegetables, light soy sauce, and sesame oil.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    price: 260,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Noodles', 'Cabbage', 'Carrot', 'Capsicum', 'Soy Sauce'],
    allergens: ['Gluten', 'Soy'],
    tags: ['Popular Noodles'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-403',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Paneer Manchurian Gravy',
    description: 'Crispy cottage cheese balls tossed in ginger garlic Manchurian sauce with fresh coriander.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    price: 320,
    discount_price: null,
    food_type: 'veg',
    spice_level: 2,
    ingredients: ['Paneer', 'Cornflour', 'Garlic', 'Ginger', 'Soy Sauce'],
    allergens: ['Dairy', 'Soy', 'Gluten'],
    tags: ['Veg Chinese'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 3,
  },
  {
    id: 'item-404',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Chicken Schezwan Fried Rice',
    description: 'Spicy wok-fried rice tossed with minced chicken, red Schezwan chili paste, and spring onions.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    price: 330,
    discount_price: null,
    food_type: 'non-veg',
    spice_level: 3,
    ingredients: ['Rice', 'Chicken', 'Schezwan Sauce', 'Egg', 'Spring Onion'],
    allergens: ['Egg', 'Soy', 'Gluten'],
    tags: ['Spicy Rice'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-405',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Steam Chicken Momos (8 pcs)',
    description: 'Steamed Himalayan dumplings stuffed with juicy minced chicken, served with spicy red chutney.',
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=600&q=80',
    price: 240,
    discount_price: 210,
    food_type: 'non-veg',
    spice_level: 2,
    ingredients: ['Minced Chicken', 'Refined Flour', 'Garlic', 'Sesame Dip'],
    allergens: ['Gluten', 'Sesame'],
    tags: ['Street Favorite'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 5,
  },
  {
    id: 'item-406',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Fried Veg Momos (8 pcs)',
    description: 'Golden crispy fried vegetable momos served with fiery chili garlic sauce.',
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=600&q=80',
    price: 210,
    discount_price: null,
    food_type: 'veg',
    spice_level: 2,
    ingredients: ['Cabbage', 'Carrot', 'Onion', 'Flour', 'Garlic Sauce'],
    allergens: ['Gluten'],
    tags: ['Crispy Veg'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 6,
  },
  {
    id: 'item-407',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Crispy Honey Chili Potato',
    description: 'Crispy potato finger fries tossed in sweet honey, garlic, red chili glaze, and toasted sesame.',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    price: 250,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Potatoes', 'Honey', 'Red Chili Flakes', 'Sesame Seeds'],
    allergens: ['Sesame', 'Soy'],
    tags: ['Sweet & Spicy'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 7,
  },
  {
    id: 'item-408',
    restaurant_id: 'rest-001',
    category_id: 'cat-104',
    name: 'Egg Hakka Noodles',
    description: 'Classic wok-tossed noodles with scrambled eggs, shredded cabbage, and bell peppers.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    price: 270,
    discount_price: null,
    food_type: 'egg',
    spice_level: 1,
    ingredients: ['Noodles', 'Scrambled Eggs', 'Cabbage', 'Soy Sauce'],
    allergens: ['Egg', 'Gluten', 'Soy'],
    tags: ['Egg Noodles'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 8,
  },

  // --- ROTIS & INDIAN BREADS (8 ITEMS) ---
  {
    id: 'item-501',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Butter Garlic Naan',
    description: 'Leavened flatbread brushed with fresh minced garlic butter and cilantro.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 85,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Refined Flour', 'Butter', 'Garlic', 'Coriander'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Tandoori Bread', 'Bestseller'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-502',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Cheese Garlic Naan',
    description: 'Tandoori naan stuffed with gooey mozzarella cheese, brushed with garlic butter.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 130,
    discount_price: 110,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Refined Flour', 'Mozzarella Cheese', 'Butter', 'Garlic'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Cheesy Special'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-503',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Tandoori Butter Roti',
    description: 'Whole wheat flatbread cooked in clay tandoor and brushed with amul butter.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 45,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Whole Wheat Flour', 'Butter'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Wheat Roti'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 3,
  },
  {
    id: 'item-504',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Butter Naan',
    description: 'Soft fluffy clay oven baked naan coated with melted butter.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 70,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Refined Flour', 'Butter', 'Yoghurt'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Classic Bread'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-505',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Laccha Paratha (Ghee)',
    description: 'Multi-layered crispy whole wheat paratha baked in tandoor with pure ghee.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 75,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Whole Wheat Flour', 'Ghee'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Layered Bread'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 5,
  },
  {
    id: 'item-506',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Stuffed Amritsari Kulcha',
    description: 'Crispy leavened bread stuffed with spiced mashed potato, onion, and pomegranate seeds.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 110,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Maida', 'Potato', 'Onion', 'Anardana', 'Butter'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Punjabi Kulcha'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 6,
  },
  {
    id: 'item-507',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Missi Roti',
    description: 'Gram flour (besan) flatbread flavored with ajwain, green chili, and onion.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 55,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Gram Flour', 'Wheat Flour', 'Ajwain', 'Ghee'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Traditional'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 7,
  },
  {
    id: 'item-508',
    restaurant_id: 'rest-001',
    category_id: 'cat-105',
    name: 'Plain Tandoori Roti',
    description: 'Traditional unbuttered whole wheat bread baked in clay tandoor.',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    price: 35,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Whole Wheat Flour'],
    allergens: ['Gluten'],
    tags: ['Low Calorie'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 8,
  },

  // --- SOUTH INDIAN & SNACKS (6 ITEMS) ---
  {
    id: 'item-601',
    restaurant_id: 'rest-001',
    category_id: 'cat-106',
    name: 'Crispy Butter Masala Dosa',
    description: 'Golden fermented rice crepe stuffed with spiced potato masala, served with coconut chutney & sambar.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    price: 180,
    discount_price: 160,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Rice Batter', 'Urad Dal', 'Potato Masala', 'Butter', 'Coconut Chutney'],
    allergens: ['Dairy'],
    tags: ['South Indian', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-602',
    restaurant_id: 'rest-001',
    category_id: 'cat-106',
    name: 'Medu Vada (2 pcs with Sambar)',
    description: 'Crispy golden fried lentil donuts served with piping hot vegetable sambar and coconut dip.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    price: 130,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Black Gram Dal', 'Black Pepper', 'Curry Leaves', 'Coconut'],
    allergens: [],
    tags: ['South Indian'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 2,
  },
  {
    id: 'item-603',
    restaurant_id: 'rest-001',
    category_id: 'cat-106',
    name: 'Paneer Cheese Dosa',
    description: 'Thin crispy crepe filled with grated spiced paneer and melted cheddar cheese.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    price: 220,
    discount_price: 199,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Dosa Batter', 'Paneer', 'Cheese', 'Butter'],
    allergens: ['Dairy'],
    tags: ['Cheesy Dosa'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 3,
  },
  {
    id: 'item-604',
    restaurant_id: 'rest-001',
    category_id: 'cat-106',
    name: 'Punjabi Samosa (2 pcs)',
    description: 'Crispy pastry shells filled with spiced potato, green peas, and cashews, served with mint chutney.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    price: 90,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Refined Flour', 'Potatoes', 'Green Peas', 'Spices', 'Mint Chutney'],
    allergens: ['Gluten'],
    tags: ['Tea Snack'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 4,
  },
  {
    id: 'item-605',
    restaurant_id: 'rest-001',
    category_id: 'cat-106',
    name: 'Pav Bhaji Special',
    description: 'Thick mashed vegetable curry topped with melted butter, served with toasted soft pav buns.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    price: 190,
    discount_price: null,
    food_type: 'veg',
    spice_level: 2,
    ingredients: ['Mixed Vegetables', 'Pav Bhaji Masala', 'Butter', 'Pav Buns', 'Lemon'],
    allergens: ['Gluten', 'Dairy'],
    tags: ['Mumbai Street Food'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 5,
  },
  {
    id: 'item-606',
    restaurant_id: 'rest-001',
    category_id: 'cat-106',
    name: 'Steam Steamed Idli (2 pcs)',
    description: 'Soft steamed rice cakes served with spicy lentil sambar and coconut chutney.',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    price: 110,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Rice', 'Urad Dal', 'Sambar', 'Chutney'],
    allergens: [],
    tags: ['Light & Healthy'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 6,
  },

  // --- DESSERTS & SWEETS (6 ITEMS) ---
  {
    id: 'item-701',
    restaurant_id: 'rest-001',
    category_id: 'cat-107',
    name: 'Hot Gulab Jamun (2 pcs)',
    description: 'Soft fried khoya dumpling soaked in warm cardamom and rose scented sugar syrup.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
    price: 110,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Khoya', 'Sugar Syrup', 'Rose Water', 'Cardamom', 'Pistachio'],
    allergens: ['Dairy', 'Gluten', 'Nuts'],
    tags: ['Classic Sweet', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-702',
    restaurant_id: 'rest-001',
    category_id: 'cat-107',
    name: 'Rasmalai Royal (2 pcs)',
    description: 'Flattened chhena patties soaked in chilled saffron and pistachio infused condensed milk.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
    price: 150,
    discount_price: 135,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Chhena', 'Condensed Milk', 'Saffron', 'Pistachio', 'Almonds'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Chilled Sweet'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-703',
    restaurant_id: 'rest-001',
    category_id: 'cat-107',
    name: 'Moong Dal Halwa (Desi Ghee)',
    description: 'Rich Rajasthani sweet made with slow-roasted yellow lentils, ghee, cashews, and saffron.',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=600&q=80',
    price: 180,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Moong Dal', 'Desi Ghee', 'Sugar', 'Cashews', 'Cardamom'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Winter Special'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 3,
  },
  {
    id: 'item-704',
    restaurant_id: 'rest-001',
    category_id: 'cat-107',
    name: 'Saffron Matka Kulfi',
    description: 'Traditional slow-churned Indian ice cream infused with kesar, pista, and cardamom in clay pot.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    price: 130,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Milk Solids', 'Saffron', 'Pistachio', 'Sugar'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Traditional Kulfi'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-705',
    restaurant_id: 'rest-001',
    category_id: 'cat-107',
    name: 'Sizzling Chocolate Brownie',
    description: 'Warm fudge brownie served on a sizzling hot plate with vanilla ice cream and hot chocolate fudge.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    price: 240,
    discount_price: 210,
    food_type: 'egg',
    spice_level: 0,
    ingredients: ['Dark Chocolate', 'Egg', 'Vanilla Ice Cream', 'Chocolate Fudge'],
    allergens: ['Dairy', 'Egg', 'Gluten'],
    tags: ['Dessert Craving'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 5,
  },
  {
    id: 'item-706',
    restaurant_id: 'rest-001',
    category_id: 'cat-107',
    name: 'Vanilla / Chocolate Scoop',
    description: 'Two scoops of premium smooth gourmet ice cream.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    price: 90,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Milk', 'Cream', 'Vanilla / Chocolate Extract'],
    allergens: ['Dairy'],
    tags: ['Ice Cream'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 6,
  },

  // --- BEVERAGES & MOCKTAILS (6 ITEMS) ---
  {
    id: 'item-801',
    restaurant_id: 'rest-001',
    category_id: 'cat-108',
    name: 'Mango Lassi (Chilled)',
    description: 'Thick creamy yoghurt beverage blended with Alphonso mango pulp and cardamom.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    price: 140,
    discount_price: 120,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Yoghurt', 'Mango Pulp', 'Sugar', 'Cardamom', 'Pistachio'],
    allergens: ['Dairy', 'Nuts'],
    tags: ['Refreshing', 'Bestseller'],
    available: true,
    featured: true,
    bestseller: true,
    sort_order: 1,
  },
  {
    id: 'item-802',
    restaurant_id: 'rest-001',
    category_id: 'cat-108',
    name: 'Fresh Mint Mojito',
    description: 'Sparkling cooler with muddled fresh mint leaves, lime juice, cane sugar syrup, and soda.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    price: 160,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Mint Leaves', 'Lime Juice', 'Soda Water', 'Crushed Ice'],
    allergens: [],
    tags: ['Mocktail'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 2,
  },
  {
    id: 'item-803',
    restaurant_id: 'rest-001',
    category_id: 'cat-108',
    name: 'Masala Masala Chaas (Buttermilk)',
    description: 'Refreshing spiced churning buttermilk with roasted cumin, rock salt, ginger, and coriander.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    price: 80,
    discount_price: null,
    food_type: 'veg',
    spice_level: 1,
    ingredients: ['Curd', 'Water', 'Roasted Cumin', 'Black Salt', 'Green Chili'],
    allergens: ['Dairy'],
    tags: ['Digestive Drink'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 3,
  },
  {
    id: 'item-804',
    restaurant_id: 'rest-001',
    category_id: 'cat-108',
    name: 'Fresh Lime Soda (Sweet/Salt)',
    description: 'Freshly squeezed lime juice served with sparkling soda or mineral water.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    price: 90,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Fresh Lime', 'Sugar Syrup / Black Salt', 'Soda Water'],
    allergens: [],
    tags: ['Hydrating'],
    available: true,
    featured: false,
    bestseller: false,
    sort_order: 4,
  },
  {
    id: 'item-805',
    restaurant_id: 'rest-001',
    category_id: 'cat-108',
    name: 'Blue Lagoon Mocktail',
    description: 'Electric blue curaçao syrup shaken with lemonade, sprite, and maraschino cherry.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    price: 180,
    discount_price: 150,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Blue Curaçao Syrup', 'Lemonade', 'Sprite', 'Crushed Ice'],
    allergens: [],
    tags: ['Party Drink'],
    available: true,
    featured: true,
    bestseller: false,
    sort_order: 5,
  },
  {
    id: 'item-806',
    restaurant_id: 'rest-001',
    category_id: 'cat-108',
    name: 'Hot Masala Chai',
    description: 'Authentic Indian milk tea brewed with ginger, cardamom, cloves, and cinnamon.',
    image: 'https://images.unsplash.com/photo-1571006682893-470a25fa1243?auto=format&fit=crop&w=600&q=80',
    price: 60,
    discount_price: null,
    food_type: 'veg',
    spice_level: 0,
    ingredients: ['Tea Leaves', 'Milk', 'Ginger', 'Cardamom', 'Sugar'],
    allergens: ['Dairy'],
    tags: ['Hot Tea'],
    available: true,
    featured: false,
    bestseller: true,
    sort_order: 6,
  },
];

export const MOCK_RESTAURANTS: Record<string, RestaurantData> = {
  skyline: {
    restaurant: {
      id: 'rest-001',
      name: 'Skyline Family Restaurant',
      slug: 'skyline',
      logo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80',
      cover_image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
      description: 'Authentic Indian delicacies, dum biryanis, Indo-Chinese favorites, and rich tandoori grills served in a warm atmosphere.',
      address: '124 Park Street, Sector 5, Kolkata, WB 700091',
      phone: '+91 98765 43210',
      opening_hours: '11:00 AM - 11:30 PM (Mon-Sun)',
      google_maps_link: 'https://maps.google.com',
      primary_color: '#d97706', // Warm Amber
      secondary_color: '#78350f',
      active: true,
      created_at: new Date().toISOString(),
    },
    categories: skylineCategories,
    menuItems: skylineMenuItems,
  },
  'gilded-palate': {
    restaurant: {
      id: 'rest-002',
      name: 'The Gilded Palate',
      slug: 'gilded-palate',
      logo: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=300&q=80',
      cover_image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80',
      description: 'Luxury Indian cuisine elevating ancient recipes with modern culinary craftsmanship.',
      address: '88 MG Road, Civil Lines, Bengaluru, KA 560001',
      phone: '+91 80 4123 9999',
      opening_hours: '12:00 PM - 11:00 PM (Daily)',
      google_maps_link: 'https://maps.google.com',
      primary_color: '#065f46', // Emerald Green
      secondary_color: '#022c22',
      active: true,
      created_at: new Date().toISOString(),
    },
    categories: [
      { id: 'cat-201', restaurant_id: 'rest-002', name: 'Royal Appetizers', description: 'Delicate kebabs and royal starters', sort_order: 1, active: true },
      { id: 'cat-202', restaurant_id: 'rest-002', name: 'Heritage Curries', description: 'Curated recipes from royal court kitchens', sort_order: 2, active: true },
      { id: 'cat-203', restaurant_id: 'rest-002', name: 'Artisanal Desserts', description: 'Handcrafted sweets infused with saffron and silver leaf', sort_order: 3, active: true },
    ],
    menuItems: [
      {
        id: 'item-201',
        restaurant_id: 'rest-002',
        category_id: 'cat-201',
        name: 'Galouti Kebab Royal',
        description: 'Melt-in-your-mouth minced lamb kebabs infused with 32 spices, served on mini saffron parathas.',
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
        price: 580,
        discount_price: null,
        food_type: 'non-veg',
        spice_level: 2,
        ingredients: ['Minced Lamb', 'Raw Papaya', 'Royal Spices', 'Ghee', 'Kewra Water'],
        allergens: ['Dairy'],
        tags: ['Awadhi Special'],
        available: true,
        featured: true,
        bestseller: true,
        sort_order: 1,
      },
      {
        id: 'item-202',
        restaurant_id: 'rest-002',
        category_id: 'cat-202',
        name: 'Nalli Nihari Awadh',
        description: 'Slow-simmered lamb shanks in rich aromatic bone marrow gravy infused with rose petals.',
        image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
        price: 720,
        discount_price: 680,
        food_type: 'non-veg',
        spice_level: 2,
        ingredients: ['Lamb Shank', 'Bone Marrow Stock', 'Rose Water', 'Vetiver', 'Kewra'],
        allergens: [],
        tags: ['Chef Recommendation'],
        available: true,
        featured: true,
        bestseller: true,
        sort_order: 1,
      },
    ],
  },
};

export function getRestaurantData(slug: string): RestaurantData | null {
  return MOCK_RESTAURANTS[slug] || MOCK_RESTAURANTS['skyline'] || null;
}
